### ISSUE TITLE
Documentation for use with hiera?

### ISSUE THREAD

**Issue by westbywest** [cernops/puppet-motd#4]
Is supplying header and news content via hiera a supported method of specifying MOTD content?  Peering into the manifest code suggests that something like this will work, at least for headers, but I'm not sure if this usage is one you anticipate.

```
---
motd_header :
  - "Welcome to %{::fqdn}, %{::operatingsystem}, %{::operatingsystemrelease}."
  - "This machine is managed by puppet.  Please tread lightly."
```

**Comment by traylenator** [comment]
This is exactly what we use:

```yaml
motd_header:
   - Welcome to %{fqdn}, %{operatingsystem}, %{operatingsystemrelease}
   - Archive of news is available in /etc/motd-archive
   - "Reminder: You have agreed to comply with the CERN computing rules"
   - http://cern.ch/ComputingRules
   - "Puppet environment: %{environment}"
   - "Puppet hostgroup: %{hostgroup}"
```
